apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: {{ name }}
    namespace: default
    labels:
        team: {{ team }}
spec:
    image: {{ image }}:{{ tag }}
    port: 8080
    liveness:
        path: {{ rootpath }}{{ path }}/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: {{ rootpath }}{{ path }}/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://www-q0.nav.no{{ rootpath }}{{ path }}
        - https://{{ path }}.nais.oera-q.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: http://appres.nav.no
        - name: API_URL
          value: https://{{ path }}-api-q.nav.no
        - name: PUBLIC_PATH
          value: {{ rootpath }}{{ path }}
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no{{ rootpath }}{{ path }}/soknad
        - name: UTILGJENGELIG
          value: "off"
        - name: TOGGLE_UTENLANDSOPPHOLD_I_PERIODEN
          value: "off"
        - name: TOGGLE_FERIEUTTAK
          value: "off"
        - name: TOGGLE_FRILANS
          value: "off"
        - name: TOGGLE_SELVSTENDIG
          value: "off"
