apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: omsorgspengerutbetaling-soknad
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /familie/sykdom-i-familien/soknad/omsorgspengerutbetaling/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /familie/sykdom-i-familien/soknad/omsorgspengerutbetaling/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    accessPolicy:
        outbound:
            external:
            - host: www.nav.no
    ingresses:
        - https://www.nav.no/familie/sykdom-i-familien/soknad/omsorgspengerutbetaling
        - https://omsorgspengerutbetaling.nais.oera.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: DECORATOR_URL
          value: https://www.nav.no/dekoratoren/?simple=true&chatbot=false
        - name: API_URL
          value: https://omsorgspengerutbetalingsoknad-api.nav.no
        - name: PUBLIC_PATH
          value: /familie/sykdom-i-familien/soknad/omsorgspengerutbetaling
        - name: LOGIN_URL
          value: https://loginservice.nav.no/login?redirect=https://www.nav.no/familie/sykdom-i-familien/soknad/omsorgspengerutbetaling/soknad
        - name: TOGGLE_LANGUAGE
          value: "on"
        - name: UTILGJENGELIG
          value: "off"
        - name: STENGT_BHG_SKOLE
          value: "on"
        - name: NYNORSK
          value: "on"
        - name: MELLOMLAGRING
          value: "on"
        - name: APPSTATUS_PROJECT_ID
          value: "ryujtq87"
        - name: APPSTATUS_DATASET
          value: "production"
