# This workflow trigger on push to any branch
name: CI / CD
on:
    push:
        paths-ignore:
            - '**.md'
            - '.gitignore'
            - 'LICENCE'
            - 'CODEOWNERS'
        branches:

env:
    IMAGE: ghcr.io/${{ github.repository }}/omsorgspengerutbetaling-soknad:${{ github.sha }}

jobs:
    test:
        name: Test Code
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Test code
              run: |
                  npm ci
                  npm run test

    build-code-and-push-docker:
        name: Build code and push docker image
        if: startsWith(github.ref, 'refs/heads/dev-') || startsWith(github.ref, 'refs/heads/master') || github.event.deployment.payload.triggered # Build and push docker if branch is either master or dev-*
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: build code
              run: |
                  npm ci
                  npm run build
            - name: Build Docker image
              run: |
                  docker build --tag ${IMAGE} .
            - name: Login to Github Package Registry
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
                  docker push ${IMAGE}

    deploy-dev-gcp:
        name: Deploy to dev-gcp
        if: startsWith(github.ref, 'refs/heads/dev-') # Build and push docker if branch is dev-*
        needs: build-code-and-push-docker # Depends on build-code-and-push-docker job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/naiserator.yml
                  VARS: nais/dev-gcp.json

    deploy-prod-gcp:
        name: deploy-prod-gcp
        if: startsWith(github.ref, 'refs/heads/master')
        needs: build-code-and-push-docker # Depends on build-code-and-push-docker job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/naiserator.yml
                  VARS: nais/prod-gcp.json
